dist: xenial
sudo: required

language: go
go:
  - 1.12.x

cache:
  directories:
    # https://docs.travis-ci.com/user/caching/
    # "If you store archives larger than a few hundred megabytes
    # in the cache, it is unlikely that youâ€™ll see a big
    # speed improvement".
    #
    # this list of directories seems to speedup things:
    #
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/.terraform.d/plugins

before_install:
  - make ci-setup

env:
  global:
    # Force-enable Go modules. Also force go to use the code in vendor/
    # These will both be unnecessary when Go 1.13 lands.
    - GO111MODULE=on
    - TF_ACC=true
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
    - CI=travis
    - CI=true

jobs:
  include:
    # NOTE: all the `stages`s  with the same name are run in parallel
    # NOTE: it seems to be faster to do all in one step
    # NOTE: use this `sudo .. su` trick in order to use
    #       the `usermod -a -G lxd` we did on the `before_install`
    - stage: Unit tests, style checks and e2e tests
      script: sudo -E su $USER -c "make ci-tests"

    # TODO: add a deployer to github releases: https://docs.travis-ci.com/user/build-stages/deploy-github-releases/

#branches:
#  only:
#    - master

after_failure:
  - sudo journalctl -e

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
